//
//  PasteboardSnapshot.swift
//  clipboardManager
//
//  A Sendable copy of what matters on the general pasteboard at one change count.
//  Captured on the main actor, processed off it.
//

import AppKit

extension NSPasteboard.PasteboardType {
    /// Attached to everything this app writes so the monitor can recognise its own writes.
    static let ownMarker = NSPasteboard.PasteboardType("com.walhallaa.clipboardManager.marker")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

struct PasteboardSnapshot: Sendable {
    var changeCount: Int
    var ownMarkerID: UUID?
    var isConcealed: Bool
    var isTransient: Bool
    var string: String?
    var rtf: Data?
    var png: Data?
    var tiff: Data?
    var fileURLs: [URL]
    var colorHex: String?
    var source: SourceApp

    private static let maxRichTextBytes = 2 * 1024 * 1024

    @MainActor
    init?(pasteboard: NSPasteboard) {
        changeCount = pasteboard.changeCount
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty else { return nil }

        ownMarkerID = pasteboard.string(forType: .ownMarker).flatMap(UUID.init(uuidString:))
        isConcealed = types.contains(.concealed)
        isTransient = types.contains(.transient) || types.contains(.autoGenerated)

        let urls = (pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL]) ?? []
        fileURLs = urls

        string = pasteboard.string(forType: .string)
        if let rtfData = pasteboard.data(forType: .rtf), rtfData.count <= Self.maxRichTextBytes {
            rtf = rtfData
        } else {
            rtf = nil
        }

        // Image bytes are only copied when nothing else will win classification
        // (files beat images, non-empty text beats images), so rich-text copies that
        // also carry a TIFF never pay for the copy.
        let hasText = !(string ?? "").trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        if urls.isEmpty, !hasText {
            png = pasteboard.data(forType: .png)
            tiff = png == nil ? pasteboard.data(forType: .tiff) : nil
        } else {
            png = nil
            tiff = nil
        }

        if let color = pasteboard.readObjects(forClasses: [NSColor.self])?.first as? NSColor {
            colorHex = color.hexString
        } else {
            colorHex = nil
        }

        if let app = NSWorkspace.shared.frontmostApplication, app.bundleIdentifier != "com.apple.loginwindow" {
            source = SourceApp(name: app.localizedName ?? "Unknown", bundleID: app.bundleIdentifier)
        } else {
            source = .unknown
        }
    }

    var hasImage: Bool { png != nil || tiff != nil }
}
